name: changed-files

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: file_changes
        uses: trilom/file-changes-action@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        run: |
          echo "Modified files:"
          for f in ${{ steps.file_changes.outputs.files_modified}}; do
            echo "$f"
          done

          echo "Modified files 2:"
          while IFS= read -r line; do
            echo "$line"
          done <"$HOME/files_modified.json"
