name: changed-files

#on:
#  push:
#    branches:
#      - experimental
#    paths:
#      - "./*"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: file_changes
        uses: trilom/file-changes-action@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        run: |
          ls ./
          cat ./files.json
          cat ./files_modified.json
          cat ./files_added.json
          cat ./files_deleted.json
