name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {
              ROS_DISTRO: melodic,
              ROS_REPO: main,
              CLANG_FORMAT_CHECK: file,
              CLANG_TIDY: true
            }
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{matrix.env}}
